### PR TITLE
Update for 3.0.0 API (TESTED)

### PR DESCRIPTION
**Pull request by Aericio**
Updated to 3.0.0 API.

Commands Disabled:
- //brush - Forms PR was denied
- //flood - Forms PR was denied
Forms PR: https://github.com/pmmp/PocketMine-MP/pull/1476

### CODE REVIEW

**Comment by teracube** [comment]
@Aericio 
please give me a download link of the zip or phar version 5.7.2 f1f3256

**Comment by Aericio** [comment]
go to my fork and download it.

**Comment by ctw452002** [comment]
@Aericio Please make it to phar...

**Comment by Aericio** [comment]
go on poggit and open pr downloads

**Pull request merged**
