### PR TITLE
Create mas.ini

### PR DESCRIPTION
**Pull request by Hungez**
Added translation for bahasa melayu

### CODE REVIEW

**Comment by Aericio** [comment]
Please revert the translation of "Submit"

**Comment by Hungez** [comment]
You mean the translation of "Submit" need to be retain in english rather than bahasa melayu?

**Comment by inxomnyaa** [comment]
Actually discussing this internally right now - as the client automatically translates the "submit" button anyways to the user's in-game language

**Comment by Hungez** [comment]
Ok, I will wait for the update then.

**Comment by inxomnyaa** [comment]
We decided to go with actual translation :) thanks for the commission

**Comment by Hungez** [comment]
Glad that i can help, always welcome.

**Pull request merged**
